### ISSUE TITLE
Global variable "curr_preds_5" is not set to empty after each epoch, it maybe a mistake, I think ?

### ISSUE THREAD

**Issue by baiyuting** [syiswell/NextItNet-Pytorch#1]
The gloabal variable curr_preds_5 in nextitrec_baseline.py is not reset to [] after each epoch, it may be a bug, I think~

**Comment by syiswell** [comment]
Thank you for your question, we have modified the code to solve the problem. Have a nice day!

**Comment by baiyuting** [comment]
ok
